version: "3"

services:
  todo-api:
    build: ./server
    ports:
      - "5000:5000"
    depends_on: 
      - todo-db
    container_name: todo-api
  
  todo-client:
    build: ./client
    ports:
      - "80:80"
    depends_on: 
      - todo-api
    container_name: todo-client
  
  todo-db:
    image: mongo
    ports:
      - "27017:27017"
    container_name: todo-db